version: 2.1
orbs:
  python: circleci/python@1.2
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

jobs:
  build:
    docker:
      - image: cimg/python:3.9-node
    steps:
      - checkout
      - run:
          name: Install system dependencies for Pillow
          command: |
            sudo apt-get update 
            sudo apt-get install -y libjpeg-dev libfreetype6-dev zlib1g-dev libjpeg-turbo8 build-essential
            sudo apt-get install -y libjpeg-turbo8
      

      - python/install-packages:
          pkg-manager: pip
          pypi-cache: true
          app-dir: ~/project
      - node/install-packages:
          pkg-manager: npm
          cache-path: ~/.npm
      - run: npm install webpack
      - run: npm run build

  test:
    docker:
      - image: cimg/python:3.6
        environment:
          DJANGO_SETTINGS_MODULE: auricroad.auricroad.settings.circleci
      - image: circleci/postgres:10-alpine-postgis
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: circle_test
      - image: circleci/redis
    working_directory: /home/circleci/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependencies-{{ checksum "requirements.txt" }}-{{ checksum "requirements-dev.txt" }}
      - run:
          command: |
            echo 'export PATH=/home/circleci/.local/bin/:$PATH' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install system dependencies for cryptography
          command: |
            sudo apt-get update 
            sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev cargo
      - run: pip install --user -r requirements-dev.txt
      - run: npm install
      - run: npm install webpack
      - run: npm run build
      - run: bandit -r auricroad/ -l --ini .bandit -x tests.py
      - run: isort --recursive --check-only --builtin django --skip-glob "*/migrations/*.py" auricroad/
      - run: prospector auricroad -X -I "auricroad/settings/*"
      - run: coverage run --source='.' manage.py test
      - run: codecov




  deploy:
    executor:
      name: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Deploy"
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              heroku/git:remote heroku-app-name=auricroad-dev.git;
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              heroku/git:remote heroku-app-name=auricroad-staging.git;
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              heroku/git:remote heroku-app-name=auricroad-prod.git;
            fi

workflows:
  version: 2.1 
  build_test_deploy:
    jobs:
      - build 
      - test:
          requires:
            - build 
      - deploy:
          requires:
            - test 
