# Generated by Django 2.1.8 on 2019-04-17 16:34

import auricroad.home.blocks
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.core.models
import wagtail.images.blocks
import wagtail.search.index


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_hotel_hotelspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('file', models.FileField(upload_to='media', verbose_name='file')),
                ('type', models.CharField(choices=[('audio', 'Audio file'), ('video', 'Video file')], max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Duration in seconds', verbose_name='duration')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('thumbnail', models.FileField(blank=True, upload_to='media_thumbnails', verbose_name='thumbnail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('collection', models.ForeignKey(default=wagtail.core.models.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Collection', verbose_name='collection')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text=None, through='taggit.TaggedItem', to='taggit.Tag', verbose_name='tags')),
                ('uploaded_by_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user')),
            ],
            options={
                'verbose_name': 'media',
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.AlterField(
            model_name='hotelspage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))]))], blank=True, null=True),
        ),
    ]
