# Generated by Django 2.1.8 on 2019-04-17 17:55

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("home", "0005_auto_20190417_1738")]

    def migrate_data_forward(apps, schema_editor):
        Hotel = apps.get_model("home", "Hotel")
        for instance in Hotel.objects.all():
            instance.save()

    def migrate_data_backward(apps, schema_editor):
        pass

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default=None,
                editable=False,
                null=True,
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.RunPython(migrate_data_forward, migrate_data_backward),
    ]
