# Generated by Django 2.1.8 on 2019-04-17 18:03

import auricroad.home.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190417_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelspage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('hotels', wagtail.core.blocks.StructBlock([('hotels', wagtail.core.blocks.ListBlock(wagtailmodelchooser.blocks.ModelChooserBlock(target_model='home.hotel')))]))], blank=True, null=True),
        ),
    ]
