# Generated by Django 2.1.8 on 2019-04-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190418_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='environment',
            field=models.CharField(choices=[('', ''), ('mountains', 'Mountains'), ('desert_riad', 'Desert Riad'), ('beach', 'Beach'), ('desert_ranch', 'Desert Ranch'), ('vineyard', 'Vineyard')], default='', max_length=50),
        ),
    ]
