# Generated by Django 2.1.8 on 2019-04-22 17:07

import auricroad.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0011_auto_20190419_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
