# Generated by Django 2.1.8 on 2019-04-25 17:39

import auricroad.home.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20190422_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoteldetailpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('intro', wagtail.core.blocks.StructBlock([('tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('tagline_bar_style', wagtail.core.blocks.ChoiceBlock(choices=[('vertical', 'vertical'), ('horizontal', 'horizontal')])), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.RichTextBlock()), ('accent_image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('image_section', wagtail.core.blocks.StructBlock([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('layout', wagtail.core.blocks.ChoiceBlock(choices=[('half_width', 'Half Width (Pick 2 Images)'), ('half_two_quarter', 'One Half Width, Two Quarter Width (Pick 3 Images)'), ('double_height_half_right', 'Two Quarters and Half Width Left, Double Height Half Right (Pick 4 Images)'), ('double_height_half_left', 'Double Height Half Left, Two Quarters and Half Width Right (Pick 4 Images)')])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])))])), ('activity_section', wagtail.core.blocks.StructBlock([('tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('activity_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=50))]))], blank=True, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
