# Generated by Django 2.1.8 on 2019-04-30 20:16

import auricroad.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtailmodelchooser.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0019_auto_20190425_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('image_section', wagtail.core.blocks.StructBlock([('rows', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('layout', wagtail.core.blocks.ChoiceBlock(choices=[('half_width', 'Half Width (Pick 2 Images)'), ('half_two_quarter', 'One Half Width, Two Quarter Width (Pick 3 Images)'), ('double_height_half_right', 'Two Quarters and Half Width Left, Double Height Half Right (Pick 4 Images)'), ('double_height_half_left', 'Double Height Half Left, Two Quarters and Half Width Right (Pick 4 Images)')])), ('images', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))])))])), ('split_image_text_card_section', wagtail.core.blocks.StructBlock([('layout_style', wagtail.core.blocks.ChoiceBlock(choices=[('image_first', 'Image First'), ('image_second', 'Image Second')])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=500)), ('body', wagtail.core.blocks.RichTextBlock()), ('button_text', wagtail.core.blocks.CharBlock(max_length=50))])), ('hotels', wagtail.core.blocks.StructBlock([('hotels', wagtail.core.blocks.ListBlock(wagtailmodelchooser.blocks.ModelChooserBlock(target_model='home.hotel')))])), ('events_footer', wagtail.core.blocks.StructBlock([('tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('body', wagtail.core.blocks.RichTextBlock()), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='hotel',
            name='events_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
