# Generated by Django 2.1.8 on 2019-05-16 17:50

import auricroad.home.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_auto_20190516_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('split_image_text_card_section', wagtail.core.blocks.StructBlock([('layout_style', wagtail.core.blocks.ChoiceBlock(choices=[('image_first', 'Image First'), ('image_second', 'Image Second')])), ('image', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=500)), ('body', wagtail.core.blocks.RichTextBlock()), ('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('full_width_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock())])), ('mission_footer', wagtail.core.blocks.StructBlock([('block_quote', wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.RichTextBlock()), ('name', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('background_text', wagtail.core.blocks.CharBlock(max_length=10, required=False)), ('accent_image', wagtail.images.blocks.ImageChooserBlock())])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True),
        ),
    ]
