# Generated by Django 2.1.8 on 2019-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_navbar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='on_scroll_image',
        ),
        migrations.AddField(
            model_name='navbar',
            name='on_scroll_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
