# Generated by Django 2.1.8 on 2019-05-22 19:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_auto_20190522_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('orange_accent_text', wagtail.core.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
    ]
