# Generated by Django 2.1.8 on 2019-05-22 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_auto_20190522_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='on_scroll_text',
        ),
        migrations.AddField(
            model_name='navbar',
            name='on_scroll_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
