# Generated by Django 2.1.8 on 2019-05-23 17:22

import auricroad.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0050_auto_20190522_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('intro', wagtail.core.blocks.StructBlock([('tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('tagline_bar_style', wagtail.core.blocks.ChoiceBlock(choices=[('vertical', 'vertical'), ('horizontal', 'horizontal')])), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('subheader_2', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.RichTextBlock()), ('accent_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('intro_video', auricroad.home.blocks.MediaBlock(icon='media', required=False)), ('finer_points_header', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('finer_points_body', wagtail.core.blocks.RichTextBlock(required=False)), ('button_text', wagtail.core.blocks.CharBlock(max_length=50, required=False))])), ('jobs_list', wagtail.core.blocks.StructBlock([('info_text', wagtail.core.blocks.RichTextBlock(required=False)), ('jobs', wagtail.core.blocks.StreamBlock([('job', wagtail.core.blocks.StructBlock([('job_title', wagtail.core.blocks.CharBlock(max_length=200)), ('job_document', wagtail.documents.blocks.DocumentChooserBlock())]))], blank=True, null=True, required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
