# Generated by Django 2.1.8 on 2019-05-29 21:44

import auricroad.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.documents.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0053_auto_20190529_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochuresPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('action_cards', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=200)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('download_file', wagtail.documents.blocks.DocumentChooserBlock(required=False))]))], blank=True, null=True, required=False))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
