# Generated by Django 2.1.8 on 2019-05-30 16:27

import auricroad.home.blocks
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0054_brochurespage'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(help_text='The label of the form field', max_length=255, verbose_name='label')),
                ('field_type', models.CharField(choices=[('singleline', 'Single line text'), ('multiline', 'Multi-line text'), ('email', 'Email'), ('number', 'Number'), ('url', 'URL'), ('checkbox', 'Checkbox'), ('checkboxes', 'Checkboxes'), ('dropdown', 'Drop down'), ('multiselect', 'Multiple select'), ('radio', 'Radio buttons'), ('date', 'Date'), ('datetime', 'Date/time'), ('hidden', 'Hidden field')], max_length=16, verbose_name='field type')),
                ('required', models.BooleanField(default=True, verbose_name='required')),
                ('choices', models.TextField(blank=True, help_text='Comma separated list of choices. Only applicable in checkboxes, radio and dropdown.', verbose_name='choices')),
                ('default_value', models.CharField(blank=True, help_text='Default value. Comma separated values supported for checkboxes.', max_length=255, verbose_name='default value')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='help text')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('to_address', models.CharField(blank=True, help_text='Optional - form submissions will be emailed to these addresses. Separate multiple addresses by comma.', max_length=255, verbose_name='to address')),
                ('from_address', models.CharField(blank=True, max_length=255, verbose_name='from address')),
                ('subject', models.CharField(blank=True, max_length=255, verbose_name='subject')),
                ('body', wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock()), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('contact_row', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('detail_icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('action_header', wagtail.core.blocks.CharBlock(max_length=50)), ('action_text', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('action_text_two', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('facebook', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('instagram', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('twitter', wagtail.core.blocks.CharBlock(max_length=50, required=False))]))], blank=True, null=True, required=False))]))], blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=50)),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.core.fields.RichTextField(blank=True)),
                ('form_intro_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='home.FormPage'),
        ),
    ]
