# Generated by Django 2.1.8 on 2019-06-06 20:15

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_basicinfopage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navbar',
            old_name='links',
            new_name='desktop_links',
        ),
        migrations.AddField(
            model_name='navbar',
            name='mobile_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('orange_accent_text', wagtail.core.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='mobile_top_nav_links',
            field=wagtail.core.fields.StreamField([('links', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('orange_accent_text', wagtail.core.blocks.BooleanBlock(required=False))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='navbar',
            name='social_icons',
            field=wagtail.core.fields.StreamField([('icons', wagtail.core.blocks.StructBlock([('link_url', wagtail.core.blocks.CharBlock(max_length=500, required=False)), ('social_type', wagtail.core.blocks.ChoiceBlock(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin')]))]))], blank=True, null=True),
        ),
    ]
