# Generated by Django 2.1.8 on 2019-06-06 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20190606_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='on_load_mobile_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
