# Generated by Django 2.1.8 on 2019-06-11 21:16

import auricroad.home.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0065_auto_20190611_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('static_body', wagtail.core.blocks.RichTextBlock(required=False)), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False))])), ('contact_row', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('detail_icon', wagtail.images.blocks.ImageChooserBlock(required=False)), ('action_header', wagtail.core.blocks.CharBlock(max_length=50)), ('action_text', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('action_text_two', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('action_text_type', wagtail.core.blocks.ChoiceBlock(choices=[('phone', 'Phone'), ('email', 'Email')], required=False)), ('action_text_two_type', wagtail.core.blocks.ChoiceBlock(choices=[('phone', 'Phone'), ('email', 'Email')], required=False)), ('facebook', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('instagram', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('twitter', wagtail.core.blocks.CharBlock(max_length=50, required=False))]))], blank=True, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
