# Generated by Django 2.1.8 on 2019-08-05 21:13

import autoslug.fields
from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0075_auto_20190805_1904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('form_section_name', models.CharField(max_length=50)),
                ('form_section_caption', models.CharField(max_length=250)),
                ('link_columns', wagtail.core.fields.StreamField([('link_column', wagtail.core.blocks.StructBlock([('column_header', wagtail.core.blocks.CharBlock(max_length=50)), ('links', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.CharBlock(max_length=250, required=False)), ('social_type', wagtail.core.blocks.ChoiceBlock(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin')], required=False))]))], blank=True, null=True, required=False))]))], blank=True, null=True)),
                ('legal_bar_links', wagtail.core.fields.StreamField([('legal_bar', wagtail.core.blocks.StructBlock([('copyright_text', wagtail.core.blocks.CharBlock(max_length=255)), ('links', wagtail.core.blocks.StreamBlock([('link', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(max_length=50)), ('internal_page', wagtail.core.blocks.PageChooserBlock(required=False)), ('external_link', wagtail.core.blocks.CharBlock(max_length=250, required=False))], template='blocks/footer_legal_link.html'))], blank=True, null=True, required=False))]))], blank=True, null=True)),
            ],
        ),
    ]
