# Generated by Django 2.1.8 on 2019-08-08 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0080_auto_20190808_0221'),
        ('home', '0076_auto_20190808_0257'),
    ]

    operations = [
    ]
