# Generated by Django 2.1.8 on 2019-08-08 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0077_contactformsettings'),
        ('home', '0081_merge_20190808_1540'),
    ]

    operations = [
    ]
