# Generated by Django 2.1.8 on 2019-08-09 18:03

import auricroad.home.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0088_auto_20190809_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presspage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('static_header', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('static_tagline', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('static_body', wagtail.core.blocks.RichTextBlock(required=False)), ('body_font', wagtail.core.blocks.ChoiceBlock(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd'), ('e', 'e'), ('f', 'f')])), ('body_size', wagtail.core.blocks.ChoiceBlock(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7)])), ('background_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('show_diamond_overlay', wagtail.core.blocks.BooleanBlock(required=False)), ('reduced_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('extended_bottom_padding', wagtail.core.blocks.BooleanBlock(required=False)), ('wider_desktop_layout', wagtail.core.blocks.BooleanBlock(required=False)), ('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('icon', wagtail.images.blocks.ImageChooserBlock()), ('header', wagtail.core.blocks.CharBlock(max_length=50)), ('subheader', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('body', wagtail.core.blocks.CharBlock(max_length=200))]))], blank=True, null=True, required=False)), ('hero_video', auricroad.home.blocks.MediaBlock(icon='media', required=False)), ('video_only_hero', wagtail.core.blocks.BooleanBlock(required=False))])), ('image_logo_link_card_section', wagtail.core.blocks.StructBlock([('cards', wagtail.core.blocks.StreamBlock([('card', wagtail.core.blocks.StructBlock([('main_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('logo_image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('header', wagtail.core.blocks.CharBlock(max_length=200)), ('tagline', wagtail.core.blocks.CharBlock(max_length=50)), ('tagline_2', wagtail.core.blocks.CharBlock(max_length=50, required=False)), ('link_url', wagtail.core.blocks.CharBlock(max_length=500))]))], blank=True, null=True, required=False))])), ('block_quote', wagtail.core.blocks.StructBlock([('body', wagtail.core.blocks.RichTextBlock()), ('name', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('title', wagtail.core.blocks.CharBlock(max_length=100, required=False)), ('background_text', wagtail.core.blocks.CharBlock(max_length=10, required=False)), ('accent_image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True),
        ),
    ]
