# Generated by Django 2.1.8 on 2019-08-16 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0098_auto_20190816_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='on_load_mobile_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
        migrations.AddField(
            model_name='navbar',
            name='on_scroll_image_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.CustomImage'),
        ),
    ]
