# Generated by Django 2.1.15 on 2020-10-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0106_auto_20201006_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsFormPage',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.FormPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.formpage',),
        ),
        migrations.AddField(
            model_name='formfield',
            name='display_label',
            field=models.CharField(blank=True, help_text='The label that the user will see. Does not need to be unique. If left blank, Label will be displayed to the user.', max_length=255, verbose_name='display label'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='full_width',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formfield',
            name='italic_help',
            field=models.BooleanField(default=False, help_text='Should the help text for the field show up in italics'),
        ),
        migrations.AddField(
            model_name='formfield',
            name='max_length',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='label',
            field=models.CharField(help_text='MUST BE UNIQUE. The label that will be associated with the data on the back-end.', max_length=255, verbose_name='label'),
        ),
    ]
