# Generated by Django 2.1.15 on 2020-10-22 16:33

from django.db import migrations, models
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0108_auto_20201009_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResponses',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, db_column='company__c', max_length=255, null=True, verbose_name='company')),
                ('last_name', models.CharField(blank=True, db_column='last_name__c', max_length=255, null=True, verbose_name='last_name')),
                ('city', models.CharField(blank=True, db_column='city__c', max_length=255, null=True, verbose_name='city')),
                ('phone', models.CharField(blank=True, db_column='phone__c', max_length=25, null=True, verbose_name='phone')),
                ('salutation', models.CharField(blank=True, db_column='salutation__c', max_length=255, null=True, verbose_name='salutation')),
                ('first_name', models.CharField(blank=True, db_column='first_name__c', max_length=255, null=True, verbose_name='first_name')),
                ('event_date', models.DateField(blank=True, db_column='event_date__c', null=True, verbose_name='event_date')),
                ('flexible_dates', models.BooleanField(db_column='flexible_dates__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='flexible_dates')),
                ('state', models.CharField(blank=True, db_column='state__c', max_length=255, null=True, verbose_name='state')),
                ('alternate_event_dates', models.DateField(blank=True, db_column='alternate_event_dates__c', null=True, verbose_name='alternate_event_dates')),
                ('email', models.EmailField(blank=True, db_column='email__c', max_length=254, null=True, verbose_name='email')),
                ('additional_comments', models.CharField(blank=True, db_column='additional_comments__c', max_length=255, null=True, verbose_name='additional_comments')),
                ('referral', models.CharField(blank=True, db_column='referral__c', max_length=255, null=True, verbose_name='referral')),
                ('number_of_guests', models.DecimalField(blank=True, db_column='number_of_guests__c', decimal_places=0, max_digits=18, null=True, verbose_name='number_of_guests')),
                ('budget', models.DecimalField(blank=True, db_column='budget__c', decimal_places=0, max_digits=18, null=True, verbose_name='budget')),
                ('address', models.CharField(blank=True, db_column='address__c', max_length=255, null=True, verbose_name='address')),
                ('zip_code', models.CharField(blank=True, db_column='zip_code__c', max_length=255, null=True, verbose_name='zip_code')),
                ('event_type', models.CharField(blank=True, db_column='event_type__c', max_length=255, null=True, verbose_name='event_type')),
                ('country', models.CharField(blank=True, db_column='country__c', max_length=255, null=True, verbose_name='country')),
                ('contact_method', models.CharField(blank=True, db_column='contact_method__c', max_length=255, null=True, verbose_name='contact_method')),
                ('submission_date', models.DateTimeField(blank=True, db_column='Submission_date__c', null=True, verbose_name='Submission date')),
            ],
            options={
                'verbose_name': 'Event Response',
                'verbose_name_plural': 'Event Responses',
                'db_table': 'eventresponses__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
