# Generated by Django 2.1.15 on 2020-10-27 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0110_auto_20201027_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventresponses',
            name='alternate_event_dates',
        ),
        migrations.RemoveField(
            model_name='eventresponses',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='eventresponses',
            name='event_date',
        ),
        migrations.AddField(
            model_name='eventresponses',
            name='alternate_date',
            field=models.DateField(blank=True, db_column='alternate_date__c', null=True, verbose_name='alternate_date'),
        ),
        migrations.AddField(
            model_name='eventresponses',
            name='number_of_guest_rooms',
            field=models.DecimalField(blank=True, db_column='number_of_guest_rooms__c', decimal_places=0, max_digits=18, null=True, verbose_name='number_of_guest_rooms'),
        ),
        migrations.AddField(
            model_name='eventresponses',
            name='number_of_nights',
            field=models.DecimalField(blank=True, db_column='number_of_nights__c', decimal_places=0, max_digits=18, null=True, verbose_name='number_of_nights'),
        ),
        migrations.AddField(
            model_name='eventresponses',
            name='petite_resort',
            field=models.CharField(blank=True, db_column='petite_resort__c', max_length=255, null=True, verbose_name='petite_resort'),
        ),
        migrations.AddField(
            model_name='eventresponses',
            name='preferred_date',
            field=models.DateField(blank=True, db_column='preferred_date__c', null=True, verbose_name='preferred_date'),
        ),
    ]
