# Generated by Django 2.1.15 on 2020-10-28 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0109_auto_20201028_1933'),
        ('home', '0111_auto_20201027_1926'),
    ]

    operations = [
    ]
