# Generated by Django 2.1.15 on 2020-10-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0112_merge_20201028_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventresponses',
            name='file_upload',
            field=models.URLField(blank=True, db_column='file_upload__c', max_length=255, null=True, verbose_name='file_upload'),
        ),
    ]
