# Generated by Django 2.1.15 on 2020-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0113_eventresponses_file_upload'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesForceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_upload', models.FileField(upload_to='uploads/%Y/%m/%d/')),
            ],
        ),
    ]
