# Generated by Django 2.1.15 on 2020-11-05 17:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0114_salesforcefile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestProfileFormPage',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.FormPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.formpage',),
        ),
        migrations.CreateModel(
            name='GuestProfileResponses',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_comments', models.CharField(blank=True, db_column='additional_comments__c', max_length=255, null=True, verbose_name='additional_comments')),
                ('allergies', models.CharField(blank=True, db_column='allergies__c', max_length=255, null=True, verbose_name='allergies')),
                ('dining_time', models.CharField(blank=True, db_column='dining_time__c', max_length=255, null=True, verbose_name='dining_time')),
                ('first_name', models.CharField(blank=True, db_column='first_name__c', max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, db_column='last_name__c', max_length=255, null=True, verbose_name='last_name')),
                ('email', models.CharField(blank=True, db_column='email__c', max_length=255, null=True, verbose_name='email')),
                ('number_of_adults', models.CharField(blank=True, db_column='number_of_adults__c', max_length=255, null=True, verbose_name='number_of_adults')),
                ('number_of_children', models.CharField(blank=True, db_column='number_of_children__c', max_length=255, null=True, verbose_name='number_of_children')),
                ('off_ranch_add_on_activities', models.CharField(blank=True, db_column='off_ranch_add_on_activities__c', max_length=255, null=True, verbose_name='off_ranch_add_on_activities')),
                ('on_ranch_add_on_activities', models.CharField(blank=True, db_column='on_ranch_add_on_activities__c', max_length=255, null=True, verbose_name='on_ranch_add_on_activities')),
                ('party_member_details', models.CharField(blank=True, db_column='party_member_details__c', max_length=255, null=True, verbose_name='party_member_details')),
                ('phone', models.CharField(blank=True, db_column='phone__c', max_length=255, null=True, verbose_name='phone')),
                ('reservation', models.CharField(blank=True, db_column='reservation__c', max_length=255, null=True, verbose_name='reservation')),
                ('spa_activities', models.CharField(blank=True, db_column='spa_activities__c', max_length=255, null=True, verbose_name='spa_activities')),
                ('special_occasions', models.CharField(blank=True, db_column='special_occasions__c', max_length=255, null=True, verbose_name='special_occasions')),
                ('transportation', models.CharField(blank=True, db_column='transportation__c', max_length=255, null=True, verbose_name='transportation')),
                ('transportation_details', models.CharField(blank=True, db_column='transportation_details__c', max_length=255, null=True, verbose_name='transportation_details')),
                ('winter_package_activites', models.CharField(blank=True, db_column='winter_package_activites__c', max_length=255, null=True, verbose_name='winter_package_activites')),
                ('submission_date', models.DateTimeField(blank=True, db_column='Submission_date__c', null=True, verbose_name='Submission date')),
            ],
            options={
                'verbose_name': 'Guest Profile Response',
                'verbose_name_plural': 'Guest Profile Responses',
                'db_table': 'guestprofileresponses__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
