# Generated by Django 2.1.15 on 2020-11-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0115_guestprofileformpage_guestprofileresponses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='additional_comments',
            field=models.CharField(blank=True, db_column='additional_comments__c', max_length=32768, null=True, verbose_name='additional_comments'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='off_ranch_add_on_activities',
            field=models.CharField(blank=True, db_column='off_ranch_add_on_activities__c', max_length=32768, null=True, verbose_name='off_ranch_add_on_activities'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='on_ranch_add_on_activities',
            field=models.CharField(blank=True, db_column='on_ranch_add_on_activities__c', max_length=32768, null=True, verbose_name='on_ranch_add_on_activities'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='party_member_details',
            field=models.CharField(blank=True, db_column='party_member_details__c', max_length=32768, null=True, verbose_name='party_member_details'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='special_occasions',
            field=models.CharField(blank=True, db_column='special_occasions__c', max_length=32768, null=True, verbose_name='special_occasions'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='transportation_details',
            field=models.CharField(blank=True, db_column='transportation_details__c', max_length=32768, null=True, verbose_name='transportation_details'),
        ),
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='winter_package_activites',
            field=models.CharField(blank=True, db_column='winter_package_activites__c', max_length=32768, null=True, verbose_name='winter_package_activites'),
        ),
    ]
