# Generated by Django 2.1.15 on 2020-11-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0116_auto_20201105_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestprofileresponses',
            name='email',
            field=models.EmailField(blank=True, db_column='email__c', max_length=255, null=True, verbose_name='email'),
        ),
    ]
