# Generated by Django 2.1.15 on 2020-11-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0117_auto_20201105_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='half_width',
            field=models.BooleanField(default=False),
        ),
    ]
