# Generated by Django 2.1.15 on 2021-01-06 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0118_formfield_half_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_1',
            field=models.CharField(blank=True, db_column='adult_bday_1__c', max_length=255, null=True, verbose_name='adult_bday_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_10',
            field=models.CharField(blank=True, db_column='adult_bday_10__c', max_length=255, null=True, verbose_name='adult_bday_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_2',
            field=models.CharField(blank=True, db_column='adult_bday_2__c', max_length=255, null=True, verbose_name='adult_bday_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_3',
            field=models.CharField(blank=True, db_column='adult_bday_3__c', max_length=255, null=True, verbose_name='adult_bday_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_4',
            field=models.CharField(blank=True, db_column='adult_bday_4__c', max_length=255, null=True, verbose_name='adult_bday_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_5',
            field=models.CharField(blank=True, db_column='adult_bday_5__c', max_length=255, null=True, verbose_name='adult_bday_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_6',
            field=models.CharField(blank=True, db_column='adult_bday_6__c', max_length=255, null=True, verbose_name='adult_bday_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_7',
            field=models.CharField(blank=True, db_column='adult_bday_7__c', max_length=255, null=True, verbose_name='adult_bday_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_8',
            field=models.CharField(blank=True, db_column='adult_bday_8__c', max_length=255, null=True, verbose_name='adult_bday_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_bday_9',
            field=models.CharField(blank=True, db_column='adult_bday_9__c', max_length=255, null=True, verbose_name='adult_bday_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_1',
            field=models.CharField(blank=True, db_column='adult_first_1__c', max_length=255, null=True, verbose_name='adult_first_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_10',
            field=models.CharField(blank=True, db_column='adult_first_10__c', max_length=255, null=True, verbose_name='adult_first_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_2',
            field=models.CharField(blank=True, db_column='adult_first_2__c', max_length=255, null=True, verbose_name='adult_first_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_3',
            field=models.CharField(blank=True, db_column='adult_first_3__c', max_length=255, null=True, verbose_name='adult_first_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_4',
            field=models.CharField(blank=True, db_column='adult_first_4__c', max_length=255, null=True, verbose_name='adult_first_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_5',
            field=models.CharField(blank=True, db_column='adult_first_5__c', max_length=255, null=True, verbose_name='adult_first_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_6',
            field=models.CharField(blank=True, db_column='adult_first_6__c', max_length=255, null=True, verbose_name='adult_first_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_7',
            field=models.CharField(blank=True, db_column='adult_first_7__c', max_length=255, null=True, verbose_name='adult_first_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_8',
            field=models.CharField(blank=True, db_column='adult_first_8__c', max_length=255, null=True, verbose_name='adult_first_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_first_9',
            field=models.CharField(blank=True, db_column='adult_first_9__c', max_length=255, null=True, verbose_name='adult_first_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_1',
            field=models.CharField(blank=True, db_column='adult_height_1__c', max_length=255, null=True, verbose_name='adult_height_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_10',
            field=models.CharField(blank=True, db_column='adult_height_10__c', max_length=255, null=True, verbose_name='adult_height_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_2',
            field=models.CharField(blank=True, db_column='adult_height_2__c', max_length=255, null=True, verbose_name='adult_height_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_3',
            field=models.CharField(blank=True, db_column='adult_height_3__c', max_length=255, null=True, verbose_name='adult_height_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_4',
            field=models.CharField(blank=True, db_column='adult_height_4__c', max_length=255, null=True, verbose_name='adult_height_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_5',
            field=models.CharField(blank=True, db_column='adult_height_5__c', max_length=255, null=True, verbose_name='adult_height_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_6',
            field=models.CharField(blank=True, db_column='adult_height_6__c', max_length=255, null=True, verbose_name='adult_height_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_7',
            field=models.CharField(blank=True, db_column='adult_height_7__c', max_length=255, null=True, verbose_name='adult_height_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_8',
            field=models.CharField(blank=True, db_column='adult_height_8__c', max_length=255, null=True, verbose_name='adult_height_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_height_9',
            field=models.CharField(blank=True, db_column='adult_height_9__c', max_length=255, null=True, verbose_name='adult_height_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_1',
            field=models.CharField(blank=True, db_column='adult_last_1__c', max_length=255, null=True, verbose_name='adult_last_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_10',
            field=models.CharField(blank=True, db_column='adult_last_10__c', max_length=255, null=True, verbose_name='adult_last_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_2',
            field=models.CharField(blank=True, db_column='adult_last_2__c', max_length=255, null=True, verbose_name='adult_last_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_3',
            field=models.CharField(blank=True, db_column='adult_last_3__c', max_length=255, null=True, verbose_name='adult_last_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_4',
            field=models.CharField(blank=True, db_column='adult_last_4__c', max_length=255, null=True, verbose_name='adult_last_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_5',
            field=models.CharField(blank=True, db_column='adult_last_5__c', max_length=255, null=True, verbose_name='adult_last_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_6',
            field=models.CharField(blank=True, db_column='adult_last_6__c', max_length=255, null=True, verbose_name='adult_last_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_7',
            field=models.CharField(blank=True, db_column='adult_last_7__c', max_length=255, null=True, verbose_name='adult_last_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_8',
            field=models.CharField(blank=True, db_column='adult_last_8__c', max_length=255, null=True, verbose_name='adult_last_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_last_9',
            field=models.CharField(blank=True, db_column='adult_last_9__c', max_length=255, null=True, verbose_name='adult_last_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_1',
            field=models.CharField(blank=True, db_column='adult_shoe_1__c', max_length=255, null=True, verbose_name='adult_shoe_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_10',
            field=models.CharField(blank=True, db_column='adult_shoe_10__c', max_length=255, null=True, verbose_name='adult_shoe_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_2',
            field=models.CharField(blank=True, db_column='adult_shoe_2__c', max_length=255, null=True, verbose_name='adult_shoe_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_3',
            field=models.CharField(blank=True, db_column='adult_shoe_3__c', max_length=255, null=True, verbose_name='adult_shoe_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_4',
            field=models.CharField(blank=True, db_column='adult_shoe_4__c', max_length=255, null=True, verbose_name='adult_shoe_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_5',
            field=models.CharField(blank=True, db_column='adult_shoe_5__c', max_length=255, null=True, verbose_name='adult_shoe_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_6',
            field=models.CharField(blank=True, db_column='adult_shoe_6__c', max_length=255, null=True, verbose_name='adult_shoe_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_7',
            field=models.CharField(blank=True, db_column='adult_shoe_7__c', max_length=255, null=True, verbose_name='adult_shoe_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_8',
            field=models.CharField(blank=True, db_column='adult_shoe_8__c', max_length=255, null=True, verbose_name='adult_shoe_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_shoe_9',
            field=models.CharField(blank=True, db_column='adult_shoe_9__c', max_length=255, null=True, verbose_name='adult_shoe_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_1',
            field=models.CharField(blank=True, db_column='adult_weight_1__c', max_length=255, null=True, verbose_name='adult_weight_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_10',
            field=models.CharField(blank=True, db_column='adult_weight_10__c', max_length=255, null=True, verbose_name='adult_weight_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_2',
            field=models.CharField(blank=True, db_column='adult_weight_2__c', max_length=255, null=True, verbose_name='adult_weight_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_3',
            field=models.CharField(blank=True, db_column='adult_weight_3__c', max_length=255, null=True, verbose_name='adult_weight_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_4',
            field=models.CharField(blank=True, db_column='adult_weight_4__c', max_length=255, null=True, verbose_name='adult_weight_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_5',
            field=models.CharField(blank=True, db_column='adult_weight_5__c', max_length=255, null=True, verbose_name='adult_weight_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_6',
            field=models.CharField(blank=True, db_column='adult_weight_6__c', max_length=255, null=True, verbose_name='adult_weight_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_7',
            field=models.CharField(blank=True, db_column='adult_weight_7__c', max_length=255, null=True, verbose_name='adult_weight_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_8',
            field=models.CharField(blank=True, db_column='adult_weight_8__c', max_length=255, null=True, verbose_name='adult_weight_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='adult_weight_9',
            field=models.CharField(blank=True, db_column='adult_weight_9__c', max_length=255, null=True, verbose_name='adult_weight_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='booked_car',
            field=models.CharField(blank=True, db_column='booked_car__c', max_length=255, null=True, verbose_name='booked_car'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_1',
            field=models.CharField(blank=True, db_column='child_bday_1__c', max_length=255, null=True, verbose_name='child_bday_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_10',
            field=models.CharField(blank=True, db_column='child_bday_10__c', max_length=255, null=True, verbose_name='child_bday_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_2',
            field=models.CharField(blank=True, db_column='child_bday_2__c', max_length=255, null=True, verbose_name='child_bday_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_3',
            field=models.CharField(blank=True, db_column='child_bday_3__c', max_length=255, null=True, verbose_name='child_bday_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_4',
            field=models.CharField(blank=True, db_column='child_bday_4__c', max_length=255, null=True, verbose_name='child_bday_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_5',
            field=models.CharField(blank=True, db_column='child_bday_5__c', max_length=255, null=True, verbose_name='child_bday_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_6',
            field=models.CharField(blank=True, db_column='child_bday_6__c', max_length=255, null=True, verbose_name='child_bday_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_7',
            field=models.CharField(blank=True, db_column='child_bday_7__c', max_length=255, null=True, verbose_name='child_bday_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_8',
            field=models.CharField(blank=True, db_column='child_bday_8__c', max_length=255, null=True, verbose_name='child_bday_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_bday_9',
            field=models.CharField(blank=True, db_column='child_bday_9__c', max_length=255, null=True, verbose_name='child_bday_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_1',
            field=models.CharField(blank=True, db_column='child_first_1__c', max_length=255, null=True, verbose_name='child_first_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_10',
            field=models.CharField(blank=True, db_column='child_first_10__c', max_length=255, null=True, verbose_name='child_first_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_2',
            field=models.CharField(blank=True, db_column='child_first_2__c', max_length=255, null=True, verbose_name='child_first_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_3',
            field=models.CharField(blank=True, db_column='child_first_3__c', max_length=255, null=True, verbose_name='child_first_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_4',
            field=models.CharField(blank=True, db_column='child_first_4__c', max_length=255, null=True, verbose_name='child_first_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_5',
            field=models.CharField(blank=True, db_column='child_first_5__c', max_length=255, null=True, verbose_name='child_first_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_6',
            field=models.CharField(blank=True, db_column='child_first_6__c', max_length=255, null=True, verbose_name='child_first_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_7',
            field=models.CharField(blank=True, db_column='child_first_7__c', max_length=255, null=True, verbose_name='child_first_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_8',
            field=models.CharField(blank=True, db_column='child_first_8__c', max_length=255, null=True, verbose_name='child_first_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_first_9',
            field=models.CharField(blank=True, db_column='child_first_9__c', max_length=255, null=True, verbose_name='child_first_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_1',
            field=models.CharField(blank=True, db_column='child_height_1__c', max_length=255, null=True, verbose_name='child_height_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_10',
            field=models.CharField(blank=True, db_column='child_height_10__c', max_length=255, null=True, verbose_name='child_height_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_2',
            field=models.CharField(blank=True, db_column='child_height_2__c', max_length=255, null=True, verbose_name='child_height_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_3',
            field=models.CharField(blank=True, db_column='child_height_3__c', max_length=255, null=True, verbose_name='child_height_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_4',
            field=models.CharField(blank=True, db_column='child_height_4__c', max_length=255, null=True, verbose_name='child_height_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_5',
            field=models.CharField(blank=True, db_column='child_height_5__c', max_length=255, null=True, verbose_name='child_height_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_6',
            field=models.CharField(blank=True, db_column='child_height_6__c', max_length=255, null=True, verbose_name='child_height_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_7',
            field=models.CharField(blank=True, db_column='child_height_7__c', max_length=255, null=True, verbose_name='child_height_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_8',
            field=models.CharField(blank=True, db_column='child_height_8__c', max_length=255, null=True, verbose_name='child_height_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_height_9',
            field=models.CharField(blank=True, db_column='child_height_9__c', max_length=255, null=True, verbose_name='child_height_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_1',
            field=models.CharField(blank=True, db_column='child_last_1__c', max_length=255, null=True, verbose_name='child_last_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_10',
            field=models.CharField(blank=True, db_column='child_last_10__c', max_length=255, null=True, verbose_name='child_last_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_2',
            field=models.CharField(blank=True, db_column='child_last_2__c', max_length=255, null=True, verbose_name='child_last_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_3',
            field=models.CharField(blank=True, db_column='child_last_3__c', max_length=255, null=True, verbose_name='child_last_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_4',
            field=models.CharField(blank=True, db_column='child_last_4__c', max_length=255, null=True, verbose_name='child_last_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_5',
            field=models.CharField(blank=True, db_column='child_last_5__c', max_length=255, null=True, verbose_name='child_last_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_6',
            field=models.CharField(blank=True, db_column='child_last_6__c', max_length=255, null=True, verbose_name='child_last_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_7',
            field=models.CharField(blank=True, db_column='child_last_7__c', max_length=255, null=True, verbose_name='child_last_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_8',
            field=models.CharField(blank=True, db_column='child_last_8__c', max_length=255, null=True, verbose_name='child_last_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_last_9',
            field=models.CharField(blank=True, db_column='child_last_9__c', max_length=255, null=True, verbose_name='child_last_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_1',
            field=models.CharField(blank=True, db_column='child_shoe_1__c', max_length=255, null=True, verbose_name='child_shoe_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_10',
            field=models.CharField(blank=True, db_column='child_shoe_10__c', max_length=255, null=True, verbose_name='child_shoe_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_2',
            field=models.CharField(blank=True, db_column='child_shoe_2__c', max_length=255, null=True, verbose_name='child_shoe_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_3',
            field=models.CharField(blank=True, db_column='child_shoe_3__c', max_length=255, null=True, verbose_name='child_shoe_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_4',
            field=models.CharField(blank=True, db_column='child_shoe_4__c', max_length=255, null=True, verbose_name='child_shoe_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_5',
            field=models.CharField(blank=True, db_column='child_shoe_5__c', max_length=255, null=True, verbose_name='child_shoe_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_6',
            field=models.CharField(blank=True, db_column='child_shoe_6__c', max_length=255, null=True, verbose_name='child_shoe_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_7',
            field=models.CharField(blank=True, db_column='child_shoe_7__c', max_length=255, null=True, verbose_name='child_shoe_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_8',
            field=models.CharField(blank=True, db_column='child_shoe_8__c', max_length=255, null=True, verbose_name='child_shoe_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_shoe_9',
            field=models.CharField(blank=True, db_column='child_shoe_9__c', max_length=255, null=True, verbose_name='child_shoe_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_1',
            field=models.CharField(blank=True, db_column='child_weight_1__c', max_length=255, null=True, verbose_name='child_weight_1'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_10',
            field=models.CharField(blank=True, db_column='child_weight_10__c', max_length=255, null=True, verbose_name='child_weight_10'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_2',
            field=models.CharField(blank=True, db_column='child_weight_2__c', max_length=255, null=True, verbose_name='child_weight_2'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_3',
            field=models.CharField(blank=True, db_column='child_weight_3__c', max_length=255, null=True, verbose_name='child_weight_3'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_4',
            field=models.CharField(blank=True, db_column='child_weight_4__c', max_length=255, null=True, verbose_name='child_weight_4'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_5',
            field=models.CharField(blank=True, db_column='child_weight_5__c', max_length=255, null=True, verbose_name='child_weight_5'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_6',
            field=models.CharField(blank=True, db_column='child_weight_6__c', max_length=255, null=True, verbose_name='child_weight_6'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_7',
            field=models.CharField(blank=True, db_column='child_weight_7__c', max_length=255, null=True, verbose_name='child_weight_7'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_8',
            field=models.CharField(blank=True, db_column='child_weight_8__c', max_length=255, null=True, verbose_name='child_weight_8'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='child_weight_9',
            field=models.CharField(blank=True, db_column='child_weight_9__c', max_length=255, null=True, verbose_name='child_weight_9'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='coffee_preference',
            field=models.CharField(blank=True, db_column='coffee_preference__c', max_length=255, null=True, verbose_name='coffee_preference'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='music_preference',
            field=models.CharField(blank=True, db_column='music_preference__c', max_length=255, null=True, verbose_name='music_preference'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='renting_car',
            field=models.CharField(blank=True, db_column='renting_car__c', max_length=255, null=True, verbose_name='renting_car'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='wine_preference',
            field=models.CharField(blank=True, db_column='wine_preference__c', max_length=255, null=True, verbose_name='wine_preference'),
        ),
        migrations.AlterField(
            model_name='eventresponses',
            name='additional_comments',
            field=models.CharField(blank=True, db_column='additional_comments__c', max_length=131072, null=True, verbose_name='additional_comments'),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='max_length',
            field=models.IntegerField(default=255, help_text="IMPORTANT!! Typically should be set to '255', but if the field is a comment text area set this to '131072'."),
        ),
    ]
