# Generated by Django 2.1.15 on 2021-03-16 21:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_auto_20210121_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsformpage',
            name='lmr_things_to_know',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
