# Generated by Django 2.1.15 on 2021-01-07 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0119_auto_20210106_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofileresponses',
            name='party_member_details',
        ),
    ]
