# Generated by Django 2.1.15 on 2021-03-16 22:06

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_eventsformpage_lmr_things_to_know'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsformpage',
            name='lmr_things_to_know',
        ),
        migrations.AddField(
            model_name='eventsformpage',
            name='events_body',
            field=wagtail.core.fields.StreamField([('things_to_know', wagtail.core.blocks.StructBlock([('hotel_name', wagtail.core.blocks.CharBlock(max_length=200)), ('hotel_info', wagtail.core.blocks.RichTextBlock())]))], blank=True, null=True),
        ),
    ]
