# Generated by Django 2.1.15 on 2021-01-14 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0120_remove_guestprofileresponses_party_member_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofileresponses',
            name='arrival_airline',
            field=models.CharField(blank=True, db_column='arrival_airline__c', max_length=255, null=True, verbose_name='arrival_airline'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='arrival_flight_date',
            field=models.CharField(blank=True, db_column='arrival_flight_date__c', max_length=255, null=True, verbose_name='arrival_flight_date'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='arrival_flight_number',
            field=models.CharField(blank=True, db_column='arrival_flight_number__c', max_length=255, null=True, verbose_name='arrival_flight_number'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='arrival_flight_time',
            field=models.CharField(blank=True, db_column='arrival_flight_time__c', max_length=255, null=True, verbose_name='arrival_flight_time'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='arrival_location',
            field=models.CharField(blank=True, db_column='arrival_location__c', max_length=255, null=True, verbose_name='arrival_location'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='departure_airline',
            field=models.CharField(blank=True, db_column='departure_airline__c', max_length=255, null=True, verbose_name='departure_airline'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='departure_flight_date',
            field=models.CharField(blank=True, db_column='departure_flight_date__c', max_length=255, null=True, verbose_name='departure_flight_date'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='departure_flight_number',
            field=models.CharField(blank=True, db_column='departure_flight_number__c', max_length=255, null=True, verbose_name='departure_flight_number'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='departure_flight_time',
            field=models.CharField(blank=True, db_column='departure_flight_time__c', max_length=255, null=True, verbose_name='departure_flight_time'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='departure_location',
            field=models.CharField(blank=True, db_column='departure_location__c', max_length=255, null=True, verbose_name='departure_location'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='party_eta',
            field=models.CharField(blank=True, db_column='party_eta__c', max_length=255, null=True, verbose_name='party_eta'),
        ),
    ]
