# Generated by Django 2.1.15 on 2021-01-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_auto_20210114_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofileresponses',
            name='winter_package_activites',
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='package_activites',
            field=models.CharField(blank=True, db_column='package_activites__c', max_length=32768, null=True, verbose_name='package_activites'),
        ),
    ]
