# Generated by Django 2.1.15 on 2021-08-10 22:08

from django.db import migrations, models
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0121_auto_20210316_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContactResponses',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, db_column='first_name__c', max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, db_column='last_name__c', max_length=255, null=True, verbose_name='last_name')),
                ('email', models.EmailField(db_column='email__c', max_length=254, verbose_name='email')),
            ],
            options={
                'verbose_name': 'AR Footer Contact Response',
                'verbose_name_plural': 'AR Footer Contact Responses',
                'db_table': 'AR_footer_contact__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
