# Generated by Django 2.1.15 on 2022-08-23 18:58

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0122_footercontactresponses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuricRoomPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('header', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(max_length=500))])), ('body_section', wagtail.core.blocks.StructBlock([('header', wagtail.core.blocks.CharBlock(max_length=500, required=False)), ('text', wagtail.core.blocks.RichTextBlock(required=False))])), ('rich_text_section', wagtail.core.blocks.RichTextBlock()), ('video_section', wagtail.core.blocks.StructBlock([('video_url', wagtail.core.blocks.CharBlock(max_length=500, required=False)), ('embed_source', wagtail.core.blocks.ChoiceBlock(choices=[('vimeo', 'Vimeo')]))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='PressInquiriesPage',
            fields=[
                ('formpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.FormPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.formpage',),
        ),
    ]
