# Generated by Django 2.1.15 on 2022-10-31 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0123_auricroompage_pressinquiriespage'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestprofileresponses',
            name='coffee_order_preferences',
            field=models.CharField(blank=True, db_column='coffee_order_preferences__c', max_length=131072, null=True, verbose_name='coffee_order_preferences'),
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='coffee_order_type',
            field=models.CharField(blank=True, db_column='coffee_order_type__c', max_length=255, null=True, verbose_name='coffee_order_type'),
        ),
    ]
