# Generated by Django 2.1.15 on 2022-11-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0124_auto_20221111_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pressinquiryresponses',
            name='requested_dates_of_stay',
        ),
        migrations.RemoveField(
            model_name='pressinquiryresponses',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='pressinquiryresponses',
            name='requested_stay',
            field=models.CharField(blank=True, db_column='requested_dates_of_stay__c', max_length=255, null=True, verbose_name='requested_dates_of_stay'),
        ),
    ]
