# Generated by Django 2.1.15 on 2023-04-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_auto_20221109_1628'),
        ('home', '0124_auto_20221111_1050'),
    ]

    operations = [
    ]
