# Generated by Django 2.1.15 on 2023-04-28 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0126_auto_20221109_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestprofileresponses',
            name='coffee_order_preferences',
        ),
        migrations.AddField(
            model_name='guestprofileresponses',
            name='cream_and_sugar',
            field=models.CharField(blank=True, db_column='cream_and_sugar__c', max_length=255, null=True, verbose_name='cream_and_sugar'),
        ),
        migrations.AddField(
            model_name='pressinquiryresponses',
            name='owner_id',
            field=models.CharField(db_column='OwnerID', default='0056g000006LjPc', max_length=255, verbose_name='owner_id'),
        ),
    ]
